export const AUDIT_ACTIONS = {
    CREATE: 'CREATE',
    UPDATE: 'UPDATE',
    DELETE: 'DELETE',
    RESTORE: 'RESTORE',
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    AUTH_FAILURE: 'AUTH_FAILURE',
    UPLOAD: 'UPLOAD',
    CLEANUP: 'CLEANUP',
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

export const AUDIT_MODULES = {
    AUTH: 'AUTH',
    DASHBOARD: 'DASHBOARD',
    PRODUCTS: 'PRODUCTS',
    BLOG: 'BLOG',
    PROJECTS: 'PROJECTS',
    RECRUITMENT: 'RECRUITMENT',
    APPLICATIONS: 'APPLICATIONS',
    COMMENTS: 'COMMENTS',
    MEDIA: 'MEDIA',
    CONTACTS: 'CONTACTS',
    USERS: 'USERS',
    ROLES: 'ROLES',
    MODULES: 'MODULES',
    LOGS: 'LOGS',
    SETTINGS: 'SETTINGS',
    NEWS: 'NEWS',
    AUDIT_LOGS: 'AUDIT_LOGS',
} as const;
