# Database
POSTGRES_HOST=sgv-cms-db
POSTGRES_PORT=5432
POSTGRES_PORT_EXTERNAL=5433
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
POSTGRES_DB=sgv_cms
DATABASE_URL=postgresql://postgres:postgres@sgv-cms-db:5432/sgv_cms

# SMTP Settings
# Mail
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USER=your_email@gmail.com
MAIL_PASSWORD=your_app_password
MAIL_FROM=your_email@gmail.com

# SEED DATA
# Tài khoản ADMIN
SEED_ADMIN_USERNAME=admin
SEED_ADMIN_PASSWORD=admin123
# Tài khoản supperadmin
SUPER_ADMIN_USERNAME=superadmin
SUPER_ADMIN_PASSWORD=Super@123

# Auth
JWT_SECRET=
