name: CI/CD

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build app
        run: NEXT_DISABLE_ESLINT=1 pnpm build

      - name: Prepare deploy files
        run: |
          rm -rf deploy
          mkdir deploy

          cp -r .next deploy/.next
          cp -r dist deploy/dist
          cp -r public deploy/public
          cp -r node_modules deploy/node_modules

          cp package.json deploy/package.json
          cp pnpm-lock.yaml deploy/pnpm-lock.yaml

      - name: Upload build to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "${{ secrets.DEPLOY_PATH }}"

      - name: Restart app
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p /home/vcxvobej/public_html/sgv_cms/tmp
            touch /home/vcxvobej/public_html/sgv_cms/tmp/restart.txt
